###
POST {{host}}/insert
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "numero_protocolo": "0000"
}

###
GET {{host}}/list
Authorization: Bearer {{token}}

###
GET {{host}}/status
Authorization: Bearer {{token}}